// src/App.tsx
import { useState, useEffect } from 'react';
import { LayoutDashboard, CalendarDays, BookOpen, History as HistoryIcon, Settings as SettingsIcon, Heart } from 'lucide-react';
import { LandingPage } from './components/LandingPage';
import { Dashboard } from './components/Dashboard';
import { DailyLog } from './components/DailyLog';
import { Recite } from './components/Recite';
import { History } from './components/History';
import { Settings } from './components/Settings';
import { getUserProfile } from './db/storage';
import type { UserProfile } from './db/storage';

function App() {
  const [showLanding, setShowLanding] = useState<boolean>(() => {
    return !localStorage.getItem('qaza_landing_dismissed');
  });
  const [activeTab, setActiveTab] = useState<'dashboard' | 'daily-log' | 'recite' | 'history' | 'settings'>('dashboard');
  const [profile, setProfile] = useState<UserProfile>(getUserProfile());
  const [refreshTrigger, setRefreshTrigger] = useState(0);

  useEffect(() => {
    document.body.classList.add('bg-[#022c22]');
    
    // Check if user is opening the app for the first time without landing page
    if (!profile.name && !showLanding) {
      setActiveTab('settings');
    }
  }, [profile.name, showLanding]);

  const handleProfileChange = (newProfile: UserProfile) => {
    setProfile(newProfile);
    setRefreshTrigger(prev => prev + 1);
  };

  const handleDataChange = () => {
    setRefreshTrigger(prev => prev + 1);
  };

  const handleShowLanding = () => {
    localStorage.removeItem('qaza_landing_dismissed');
    setShowLanding(true);
  };

  // If landing page needs to be shown, render it exclusively
  if (showLanding) {
    return (
      <LandingPage
        onStart={() => {
          localStorage.setItem('qaza_landing_dismissed', 'true');
          setShowLanding(false);
          if (!profile.name) {
            setActiveTab('settings');
          } else {
            setActiveTab('dashboard');
          }
        }}
      />
    );
  }

  return (
    <div className="min-h-screen bg-[#022c22] text-[#e2e8f0] font-sans flex flex-col items-center justify-start pb-24 selection:bg-[#d4af37]/30">
      {/* App Container */}
      <div className="w-full max-w-md md:max-w-3xl lg:max-w-5xl px-4 flex flex-col min-h-screen relative">
        
        {/* Elegant Islamic Header */}
        <header className="py-5 flex items-center justify-between border-b border-emerald-950/40 mb-6 bg-[#022c22]/80 backdrop-blur-md sticky top-0 z-40">
          <div className="flex items-center space-x-3">
            {/* Mosque dome silhouette avatar */}
            <div className="w-10 h-10 rounded-xl bg-gradient-to-br from-[#d4af37]/20 to-emerald-900/40 border border-[#d4af37]/30 flex items-center justify-center relative shadow-inner">
              <span className="text-xl font-bold text-[#d4af37] font-outfit">ق</span>
            </div>
            <div>
              <h1 className="text-lg font-bold font-outfit tracking-wide text-white leading-tight">Qaza Tracker</h1>
              <p className="text-[9px] uppercase tracking-widest text-[#d4af37]/80 font-bold">Missed Prayer Tracker</p>
            </div>
          </div>
          
          <div className="px-3 py-1 rounded-full bg-emerald-950/60 border border-emerald-900/30">
            <span className="text-[10px] text-[#10b981] font-extrabold flex items-center space-x-1">
              <span className="w-1.5 h-1.5 rounded-full bg-[#10b981] animate-pulse mr-1"></span>
              Offline Ready
            </span>
          </div>
        </header>

        {/* First time user greeting */}
        {!profile.name && activeTab === 'settings' && (
          <div className="mb-4 p-4 bg-emerald-950/40 border border-[#d4af37]/30 rounded-2xl text-center animate-pulse">
            <h2 className="text-sm font-bold text-[#d4af37] mb-1">Welcome to Qaza Tracker</h2>
            <p className="text-xs text-[#94a3b8]">Please enter your name below to customize your tracking companion.</p>
          </div>
        )}

        {/* Content Area */}
        <main className="flex-1 w-full animate-fade-in">
          {activeTab === 'dashboard' && (
            <Dashboard profile={profile} onDataChange={handleDataChange} />
          )}
          {activeTab === 'daily-log' && (
            <DailyLog profile={profile} onDataChange={handleDataChange} />
          )}
          {activeTab === 'recite' && (
            <Recite onDataChange={handleDataChange} />
          )}
          {activeTab === 'history' && (
            <History profile={profile} refreshTrigger={refreshTrigger} />
          )}
          {activeTab === 'settings' && (
            <div className="space-y-6">
              <Settings onProfileChange={handleProfileChange} />
              
              {/* Optional Welcome screen trigger in Settings */}
              <div className="glass-panel rounded-2xl p-5 border border-emerald-900/40">
                <h3 className="text-sm font-bold text-[#d4af37] uppercase tracking-wider mb-2">Welcome Screen</h3>
                <p className="text-[10px] text-[#94A3B8] mb-4">View the splash landing page with benefits and Hadith warnings.</p>
                <button
                  onClick={handleShowLanding}
                  className="w-full py-2.5 bg-emerald-950/60 border border-emerald-900/40 hover:bg-[#d4af37]/10 hover:border-[#d4af37]/50 active:scale-95 transition-all text-[#d4af37] rounded-xl text-xs font-bold cursor-pointer"
                >
                  Show Welcome Screen
                </button>
              </div>
            </div>
          )}
        </main>

        {/* Bottom Navigation Bar */}
        <nav className="fixed bottom-4 left-4 right-4 max-w-md md:max-w-lg mx-auto glass-panel-active rounded-2xl border border-[#d4af37]/25 shadow-2xl z-50 overflow-hidden">
          <div className="grid grid-cols-5 h-16">
            
            {/* Dashboard Tab */}
            <button
              onClick={() => setActiveTab('dashboard')}
              className={`flex flex-col items-center justify-center transition-all duration-200 cursor-pointer ${
                activeTab === 'dashboard' 
                  ? 'text-[#d4af37] bg-emerald-950/30' 
                  : 'text-[#94a3b8] hover:text-[#e2e8f0]'
              }`}
            >
              <LayoutDashboard className={`h-4.5 w-4.5 ${activeTab === 'dashboard' ? 'scale-110 drop-shadow-[0_0_8px_rgba(212,175,55,0.4)]' : ''}`} />
              <span className="text-[8px] font-bold font-outfit mt-1 uppercase tracking-wider">Tracker</span>
            </button>

            {/* Daily Log Tab */}
            <button
              onClick={() => setActiveTab('daily-log')}
              className={`flex flex-col items-center justify-center transition-all duration-200 cursor-pointer ${
                activeTab === 'daily-log' 
                  ? 'text-[#d4af37] bg-emerald-950/30' 
                  : 'text-[#94a3b8] hover:text-[#e2e8f0]'
              }`}
            >
              <CalendarDays className={`h-4.5 w-4.5 ${activeTab === 'daily-log' ? 'scale-110 drop-shadow-[0_0_8px_rgba(212,175,55,0.4)]' : ''}`} />
              <span className="text-[8px] font-bold font-outfit mt-1 uppercase tracking-wider">Daily Log</span>
            </button>

            {/* Recite Tab */}
            <button
              onClick={() => setActiveTab('recite')}
              className={`flex flex-col items-center justify-center transition-all duration-200 cursor-pointer ${
                activeTab === 'recite' 
                  ? 'text-[#d4af37] bg-emerald-950/30' 
                  : 'text-[#94a3b8] hover:text-[#e2e8f0]'
              }`}
            >
              <BookOpen className={`h-4.5 w-4.5 ${activeTab === 'recite' ? 'scale-110 drop-shadow-[0_0_8px_rgba(212,175,55,0.4)]' : ''}`} />
              <span className="text-[8px] font-bold font-outfit mt-1 uppercase tracking-wider">Recite</span>
            </button>

            {/* History Tab */}
            <button
              onClick={() => setActiveTab('history')}
              className={`flex flex-col items-center justify-center transition-all duration-200 cursor-pointer ${
                activeTab === 'history' 
                  ? 'text-[#d4af37] bg-emerald-950/30' 
                  : 'text-[#94a3b8] hover:text-[#e2e8f0]'
              }`}
            >
              <HistoryIcon className={`h-4.5 w-4.5 ${activeTab === 'history' ? 'scale-110 drop-shadow-[0_0_8px_rgba(212,175,55,0.4)]' : ''}`} />
              <span className="text-[8px] font-bold font-outfit mt-1 uppercase tracking-wider">History</span>
            </button>

            {/* Settings Tab */}
            <button
              onClick={() => setActiveTab('settings')}
              className={`flex flex-col items-center justify-center transition-all duration-200 cursor-pointer ${
                activeTab === 'settings' 
                  ? 'text-[#d4af37] bg-emerald-950/30' 
                  : 'text-[#94a3b8] hover:text-[#e2e8f0]'
              }`}
            >
              <SettingsIcon className={`h-4.5 w-4.5 ${activeTab === 'settings' ? 'scale-110 drop-shadow-[0_0_8px_rgba(212,175,55,0.4)]' : ''}`} />
              <span className="text-[8px] font-bold font-outfit mt-1 uppercase tracking-wider">Settings</span>
            </button>

          </div>
        </nav>

        {/* Footer info (only visible at bottom of scrollable views) */}
        <footer className="text-center text-[9px] text-emerald-900/60 mt-12 mb-6">
          <p className="flex items-center justify-center">
            Made with <Heart className="h-2 w-2 mx-1 text-red-800" /> for the Ummah
          </p>
          <p className="mt-1">Qaza Prayer Tracker © 2026</p>
        </footer>

      </div>
    </div>
  );
}

export default App;

// frontend/src/App.vue
<script setup lang="ts">
import { ref, computed, onMounted, onUnmounted } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '@/stores/auth'
import {
  LayoutDashboard,
  CalendarDays,
  BookOpen,
  Sparkles,
  History as HistoryIcon,
  Settings as SettingsIcon,
  Heart,
  User,
  LogOut,
  ChevronDown,
  MapPin
} from 'lucide-vue-next'

const route = useRoute()
const router = useRouter()
const authStore = useAuthStore()

const isPublicRoute = computed(() => route.meta.public === true)
const showProfileMenu = ref(false)
const profileMenuRef = ref<HTMLElement | null>(null)

const navItems = [
  { name: 'dashboard', label: 'Tracker', path: '/dashboard', icon: LayoutDashboard },
  { name: 'daily-log', label: 'Daily Log', path: '/daily-log', icon: CalendarDays },
  { name: 'quran', label: 'Quran Reader', path: '/quran', icon: BookOpen },
  { name: 'ai', label: 'AI Scholar', path: '/ai', icon: Sparkles },
  { name: 'history', label: 'History & Stats', path: '/history', icon: HistoryIcon },
  { name: 'settings', label: 'Settings', path: '/settings', icon: SettingsIcon },
]

function toggleProfileMenu() {
  showProfileMenu.value = !showProfileMenu.value
}

function handleMenuAction(path: string) {
  showProfileMenu.value = false
  router.push(path)
}

function handleSignOut() {
  showProfileMenu.value = false
  authStore.signOut()
  router.push('/login')
}

function handleClickOutside(event: MouseEvent) {
  if (profileMenuRef.value && !profileMenuRef.value.contains(event.target as Node)) {
    showProfileMenu.value = false
  }
}

onMounted(() => {
  document.addEventListener('click', handleClickOutside)
})

onUnmounted(() => {
  document.removeEventListener('click', handleClickOutside)
})
</script>

<template>
  <div class="min-h-screen bg-[#022c22] text-[#e2e8f0] font-sans flex flex-col md:flex-row justify-start selection:bg-[#d4af37]/30">
    
    <!-- DESKTOP SIDEBAR (Visible on md+ screens) -->
    <aside
      v-if="!isPublicRoute"
      class="hidden md:flex md:flex-col md:fixed md:inset-y-0 md:left-0 md:w-64 bg-[#0a3d2e]/90 backdrop-blur-2xl border-r border-emerald-800/40 z-50 p-5 justify-between shadow-2xl"
    >
      <!-- Logo & Branding -->
      <div class="space-y-6">
        <div class="flex items-center gap-3 cursor-pointer group" @click="router.push('/dashboard')">
          <div class="w-11 h-11 rounded-2xl bg-gradient-to-br from-[#d4af37]/30 to-emerald-950/80 border border-[#d4af37]/50 flex items-center justify-center shadow-lg group-hover:scale-105 transition-transform duration-200">
            <span class="text-2xl font-bold text-[#d4af37] font-arabic">ق</span>
          </div>
          <div>
            <h1 class="text-lg font-extrabold tracking-wide text-white leading-tight">Qaza Tracker</h1>
            <p class="text-[10px] text-[#d4af37] font-semibold tracking-wider uppercase">Prayer Accountability</p>
          </div>
        </div>

        <!-- City / Sync Info Card -->
        <div class="p-3 bg-emerald-950/80 border border-emerald-800/60 rounded-2xl flex items-center justify-between">
          <div class="flex items-center gap-2 truncate text-xs text-emerald-200">
            <MapPin class="w-3.5 h-3.5 text-[#d4af37] shrink-0" />
            <span class="truncate font-medium">{{ authStore.profile?.city || 'Location Pending' }}</span>
          </div>
          <div class="flex items-center gap-1.5 px-2 py-0.5 rounded-full bg-emerald-900/60 border border-emerald-700/40 text-[9px] text-emerald-300 font-semibold shrink-0">
            <span class="w-1.5 h-1.5 rounded-full bg-[#10b981] animate-pulse"></span>
            <span>Live</span>
          </div>
        </div>

        <!-- Navigation Links -->
        <nav class="space-y-1.5">
          <button
            v-for="item in navItems"
            :key="item.name"
            @click="router.push(item.path)"
            :class="[
              'w-full flex items-center gap-3.5 px-3.5 py-3 rounded-2xl text-xs font-semibold transition-all duration-200 cursor-pointer text-left',
              route.path === item.path
                ? 'bg-gradient-to-r from-[#d4af37]/25 to-emerald-900/50 text-white border border-[#d4af37]/40 shadow-md translate-x-1'
                : 'text-emerald-200/70 hover:text-white hover:bg-emerald-900/40'
            ]"
          >
            <component
              :is="item.icon"
              class="w-4.5 h-4.5 transition-transform"
              :class="route.path === item.path ? 'text-[#d4af37] scale-110' : 'text-emerald-400'"
            />
            <span class="tracking-wide">{{ item.label }}</span>
          </button>
        </nav>
      </div>

      <!-- User Profile Drawer & Logout Footer -->
      <div class="pt-4 border-t border-emerald-800/40 space-y-3">
        <div class="flex items-center justify-between p-2 rounded-2xl bg-emerald-950/60 border border-emerald-800/40">
          <div class="flex items-center gap-2.5 min-w-0">
            <div class="w-8 h-8 rounded-xl bg-gradient-to-tr from-[#d4af37] to-amber-200 text-[#022c22] flex items-center justify-center font-bold text-xs shadow-inner shrink-0">
              <User class="w-4 h-4" />
            </div>
            <div class="truncate">
              <p class="text-xs font-bold text-white truncate">{{ authStore.profile?.name || 'Fellow Muslim' }}</p>
              <p class="text-[10px] text-emerald-300/70 truncate">Logged in</p>
            </div>
          </div>
          <button
            @click="handleSignOut"
            title="Log Out"
            class="p-2 text-emerald-400 hover:text-red-400 hover:bg-red-950/40 rounded-xl transition cursor-pointer"
          >
            <LogOut class="w-4 h-4" />
          </button>
        </div>

        <p class="text-center text-[10px] text-emerald-500/60 flex items-center justify-center gap-1">
          Made with <Heart class="w-2.5 h-2.5 text-red-500" /> for the Ummah
        </p>
      </div>
    </aside>

    <!-- MAIN CONTENT CONTAINER (Aligned with responsive padding) -->
    <div :class="['flex-1 flex flex-col min-h-screen relative w-full', !isPublicRoute ? 'md:pl-64' : '']">
      
      <!-- Top Mobile/Tablet Header -->
      <header
        v-if="!isPublicRoute"
        class="py-3 px-4 sm:px-6 flex items-center justify-between border-b border-emerald-900/40 bg-[#022c22]/95 backdrop-blur-md sticky top-0 z-40 md:hidden"
      >
        <!-- Mobile Logo -->
        <div class="flex items-center space-x-2.5 cursor-pointer" @click="router.push('/dashboard')">
          <div class="w-8 h-8 rounded-xl bg-gradient-to-br from-[#d4af37]/20 to-emerald-900/40 border border-[#d4af37]/40 flex items-center justify-center shadow-inner">
            <span class="text-base font-bold text-[#d4af37] font-arabic">ق</span>
          </div>
          <div>
            <h1 class="text-sm font-bold text-white leading-tight">Qaza Tracker</h1>
            <p class="text-[9px] text-[#d4af37] font-medium">{{ authStore.profile?.city || 'Live' }}</p>
          </div>
        </div>

        <!-- Mobile Profile Dropdown -->
        <div class="relative" ref="profileMenuRef">
          <button
            @click.stop="toggleProfileMenu"
            class="flex items-center gap-1.5 py-1 px-2.5 rounded-2xl bg-emerald-950/90 border border-emerald-700/60 transition cursor-pointer"
          >
            <div class="w-6 h-6 rounded-lg bg-gradient-to-tr from-[#d4af37] to-amber-200 text-[#022c22] flex items-center justify-center font-bold text-[10px]">
              <User class="w-3 h-3" />
            </div>
            <ChevronDown class="w-3 h-3 text-emerald-400" />
          </button>

          <!-- Mobile Dropdown Card -->
          <transition
            enter-active-class="transition duration-150 ease-out"
            enter-from-class="transform scale-95 opacity-0"
            enter-to-class="transform scale-100 opacity-100"
            leave-active-class="transition duration-100 ease-in"
            leave-from-class="transform scale-100 opacity-100"
            leave-to-class="transform scale-95 opacity-0"
          >
            <div
              v-if="showProfileMenu"
              class="absolute right-0 mt-2 w-56 bg-[#0a3d2e]/95 backdrop-blur-2xl border border-emerald-700/60 rounded-2xl shadow-2xl p-2 z-50 divide-y divide-emerald-900/60 text-xs"
            >
              <div class="p-2.5">
                <p class="font-bold text-white text-xs truncate">{{ authStore.profile?.name || 'Fellow Muslim' }}</p>
                <p class="text-[10px] text-emerald-300/80 truncate">{{ authStore.profile?.city || 'Location not set' }}</p>
              </div>

              <div class="py-1">
                <button
                  @click="handleMenuAction('/settings')"
                  class="w-full flex items-center gap-2 px-3 py-2 rounded-xl text-emerald-100 hover:text-[#d4af37] hover:bg-emerald-900/60 transition cursor-pointer text-left"
                >
                  <SettingsIcon class="w-3.5 h-3.5 text-emerald-400" />
                  <span>Account Settings</span>
                </button>
              </div>

              <div class="pt-1">
                <button
                  @click="handleSignOut"
                  class="w-full flex items-center gap-2 px-3 py-2 rounded-xl text-red-300 hover:text-red-200 hover:bg-red-950/60 transition cursor-pointer text-left font-medium"
                >
                  <LogOut class="w-3.5 h-3.5 text-red-400" />
                  <span>Log Out</span>
                </button>
              </div>
            </div>
          </transition>
        </div>
      </header>

      <!-- VIEW SLOT -->
      <main :class="['flex-1 w-full max-w-5xl mx-auto px-4 sm:px-6 lg:px-8 py-4 animate-fade-in', (route.path === '/ai' || route.path === '/quran') ? 'pb-4 flex flex-col' : 'pb-28 md:pb-12']">
        <RouterView />
      </main>

      <!-- MOBILE BOTTOM FLOATING NAVIGATION (Hidden on /ai and /quran) -->
      <nav
        v-if="!isPublicRoute && route.path !== '/ai' && route.path !== '/quran'"
        class="md:hidden fixed bottom-3 left-4 right-4 max-w-md mx-auto bg-[#0a3d2e]/95 backdrop-blur-2xl border border-emerald-700/60 rounded-3xl z-50 p-1.5 shadow-2xl"
      >
        <div class="grid grid-cols-6 h-12">
          <button
            v-for="item in navItems"
            :key="item.name"
            @click="router.push(item.path)"
            :title="item.label"
            :class="[
              'flex items-center justify-center rounded-2xl transition-all duration-200 cursor-pointer relative',
              route.path === item.path
                ? 'bg-emerald-950 text-[#d4af37] border border-[#d4af37]/40 shadow-inner'
                : 'text-emerald-300/70 hover:text-white hover:bg-emerald-900/40'
            ]"
          >
            <component
              :is="item.icon"
              class="w-5 h-5 transition-transform"
              :class="route.path === item.path ? 'scale-115 text-[#d4af37] drop-shadow-[0_0_8px_rgba(212,175,55,0.5)]' : ''"
            />
            <!-- Tiny Active Indicator Dot -->
            <span
              v-if="route.path === item.path"
              class="absolute bottom-1 w-1 h-1 rounded-full bg-[#d4af37] animate-pulse"
            ></span>
          </button>
        </div>
      </nav>

    </div>
  </div>
</template>
